/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package GUI;

import java.sql.SQLException;
import java.awt.Dimension;
import java.awt.Toolkit;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.Statement;
import java.sql.ResultSet;
import java.util.HashMap;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.table.DefaultTableModel;
import net.sf.jasperreports.engine.JasperFillManager;
import net.sf.jasperreports.engine.JasperPrint;
import net.sf.jasperreports.view.JasperViewer;


/**
 *
 * @author rafim
 */
public class InventarisAset extends javax.swing.JFrame {

    private Connection con;
    private Statement stat;
    private ResultSet res;

    /**
     * Creates new form InventarisAset
     */
    public InventarisAset() {
        initComponents();
        setTitle("Inventaris Aset");
        koneksi();
        tabel1();
        tabel2();
        //membuat layout tampil di tengah pada saat di tampilkan
        Dimension screenSize = Toolkit.getDefaultToolkit().getScreenSize();
        Dimension frameSize = getSize();
        setLocation(
                (screenSize.width - frameSize.width) / 2,
                (screenSize.height - frameSize.height) / 2);
    }

    private void koneksi() {
        try {
            Class.forName("com.mysql.cj.jdbc.Driver");
            con = DriverManager.getConnection("jdbc:mysql://localhost:3306/inventaris_aset", "root", "");
            stat = con.createStatement();
        } catch (ClassNotFoundException | SQLException e) {
            JOptionPane.showMessageDialog(null, e);
        }
    }

    private void kosongkan() {
        tfkodebarang.setText("");
        tfnamabarang.setText("");
        tftanggalmasuk.setText("");
        tftanggalkeluar.setText("");
        tfjumlah.setText("");
        tfkondisi.setText("");
        tfkodebarang.requestFocus();
    }

    private void tabel1() {
        DefaultTableModel t = new DefaultTableModel();
        t.addColumn("Kode Barang");
        t.addColumn("Nama Barang");
        t.addColumn("Tanggal Masuk");
        t.addColumn("Jumlah");
        t.addColumn("Kondisi");
        tblbarangmasuk.setModel(t);
        try {
            res = stat.executeQuery("select * from barang_masuk");
            while (res.next()) {
                t.addRow(new Object[]{res.getString("kode_barang"),
                    res.getString("nama_barang"),
                    res.getString("tanggal_masuk"),
                    res.getString("jumlah"),
                    res.getString("kondisi")
                });
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(rootPane, e);
        }
    }

    private void tabel2() {
        DefaultTableModel t = new DefaultTableModel();
        t.addColumn("Kode Barang");
        t.addColumn("Nama Barang");
        t.addColumn("Tanggal Masuk");
        t.addColumn("Tanggal Keluar");
        t.addColumn("Jumlah");
        t.addColumn("Kondisi");
        tblbarangkeluar.setModel(t);
        try {
            res = stat.executeQuery("select * from barang_keluar");
            while (res.next()) {
                t.addRow(new Object[]{res.getString("kode_barang"),
                    res.getString("nama_barang"),
                    res.getString("tanggal_masuk"),
                    res.getString("tanggal_keluar"),
                    res.getString("jumlah"),
                    res.getString("kondisi")
                });
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(rootPane, e);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel10 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblbarangmasuk = new javax.swing.JTable();
        btnedit = new javax.swing.JButton();
        btncetak = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tblbarangkeluar = new javax.swing.JTable();
        btnhapus = new javax.swing.JButton();
        btncetak2 = new javax.swing.JButton();
        btnedit1 = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        tftanggalkeluar = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        tfjumlah = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        tfkondisi = new javax.swing.JTextField();
        btninputbarangmasuk = new javax.swing.JButton();
        btnhapus1 = new javax.swing.JButton();
        btninputbarangkeluar = new javax.swing.JButton();
        btnhapus2 = new javax.swing.JButton();
        btnkeluar = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        tftanggalmasuk = new javax.swing.JTextField();
        tfnamabarang = new javax.swing.JTextField();
        tfkodebarang = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel1.setText("PROGRAM INVENTARIS ASET");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(277, 18, 250, 25);

        jPanel2.setBackground(new java.awt.Color(0, 204, 204));

        jLabel10.setFont(new java.awt.Font("Segoe UI", 1, 10)); // NOI18N
        jLabel10.setText("INPUT/REVIEW BARANG");

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 10)); // NOI18N
        jLabel2.setText("Tabel Barang Masuk");

        tblbarangmasuk.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tblbarangmasuk.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblbarangmasukMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tblbarangmasuk);

        btnedit.setText("EDIT (I)");
        btnedit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btneditActionPerformed(evt);
            }
        });

        btncetak.setText("CETAK (I)");
        btncetak.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btncetakActionPerformed(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 10)); // NOI18N
        jLabel4.setText("Tabel Barang Keluar");

        tblbarangkeluar.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tblbarangkeluar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblbarangkeluarMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(tblbarangkeluar);

        btnhapus.setText("RISET");
        btnhapus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnhapusActionPerformed(evt);
            }
        });

        btncetak2.setText(" CETAK (II)");
        btncetak2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btncetak2ActionPerformed(evt);
            }
        });

        btnedit1.setText("EDIT (II)");
        btnedit1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnedit1ActionPerformed(evt);
            }
        });

        jLabel7.setText("Tanggal Keluar");

        tftanggalkeluar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tftanggalkeluarActionPerformed(evt);
            }
        });

        jLabel8.setText("Jumlah");

        jLabel9.setText("Kondisi");

        btninputbarangmasuk.setText("INPUT BARANG MASUK");
        btninputbarangmasuk.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btninputbarangmasukActionPerformed(evt);
            }
        });

        btnhapus1.setText("HAPUS (I)");
        btnhapus1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnhapus1ActionPerformed(evt);
            }
        });

        btninputbarangkeluar.setText("INPUT BARANG KELUAR");
        btninputbarangkeluar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btninputbarangkeluarActionPerformed(evt);
            }
        });

        btnhapus2.setText("HAPUS (II)");
        btnhapus2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnhapus2ActionPerformed(evt);
            }
        });

        btnkeluar.setText("KELUAR");
        btnkeluar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnkeluarActionPerformed(evt);
            }
        });

        jPanel3.setBackground(new java.awt.Color(102, 204, 255));

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 44, Short.MAX_VALUE)
        );

        tftanggalmasuk.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tftanggalmasukActionPerformed(evt);
            }
        });

        tfnamabarang.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfnamabarangActionPerformed(evt);
            }
        });

        tfkodebarang.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfkodebarangActionPerformed(evt);
            }
        });

        jLabel6.setText("Tanggal Masuk");

        jLabel5.setText("Nama Barang");

        jLabel3.setText("Kode Barang");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(17, 17, 17)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, 109, Short.MAX_VALUE)
                            .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(54, 54, 54)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(tfjumlah, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(tftanggalmasuk, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(tfnamabarang, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(tfkodebarang, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(tftanggalkeluar, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(tfkondisi, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(btninputbarangmasuk, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btninputbarangkeluar, javax.swing.GroupLayout.DEFAULT_SIZE, 172, Short.MAX_VALUE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnhapus2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnhapus1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(64, 64, 64)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnedit)
                        .addGap(18, 18, 18)
                        .addComponent(btncetak)
                        .addGap(78, 78, 78))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 398, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(btnhapus)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(btnedit1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btncetak2)
                                .addGap(12, 12, 12)))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(btnkeluar, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 398, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addContainerGap(66, Short.MAX_VALUE))))
            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addGap(76, 76, 76)
                .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btnkeluar))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(83, 83, 83)
                        .addComponent(jLabel10)))
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(15, 15, 15)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(tfkodebarang, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel3))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel5)
                            .addComponent(tfnamabarang, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(15, 15, 15)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel6)
                                    .addComponent(tftanggalmasuk, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(27, 27, 27)
                                .addComponent(jLabel7))
                            .addComponent(tftanggalkeluar, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addGap(9, 9, 9)
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnedit)
                            .addComponent(btncetak)))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(17, 17, 17)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel8)
                            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jLabel4)
                                .addComponent(tfjumlah, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addGap(3, 3, 3)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(btnedit1)
                                .addComponent(btncetak2))
                            .addComponent(btnhapus)))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(tfkondisi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel9))
                        .addGap(40, 40, 40)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnhapus1)
                            .addComponent(btninputbarangmasuk))
                        .addGap(20, 20, 20)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnhapus2)
                            .addComponent(btninputbarangkeluar))))
                .addContainerGap(87, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel1);
        jPanel1.setBounds(10, 10, 830, 550);

        setSize(new java.awt.Dimension(871, 575));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void tfkodebarangActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfkodebarangActionPerformed
        // TODO add your handling code here:
        try {
            res = stat.executeQuery("select * from barang_masuk where " + "kode_barang='" + tfkodebarang.getText()
                + "'");
            while (res.next()) {
                tfnamabarang.setText(res.getString("nama_barang"));
                tftanggalmasuk.setText(res.getString("tanggal_masuk"));
                tfjumlah.setText(res.getString("jumlah"));
                tfkondisi.setText(res.getString("kondisi"));
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(rootPane, e);
        }
    }//GEN-LAST:event_tfkodebarangActionPerformed

    private void tfnamabarangActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfnamabarangActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfnamabarangActionPerformed

    private void tftanggalmasukActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tftanggalmasukActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tftanggalmasukActionPerformed

    private void btnkeluarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnkeluarActionPerformed
        // TODO add your handling code here:
        JOptionPane.showMessageDialog(null, "Anda Keluar");
        System.exit(0);
    }//GEN-LAST:event_btnkeluarActionPerformed

    private void btnhapus2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnhapus2ActionPerformed
        int selectedRowIndex = tblbarangkeluar.getSelectedRow();
        if (selectedRowIndex != -1) {
            int confirmResult = JOptionPane.showConfirmDialog(null, "Apakah Anda Yakin Untuk Menghapus Data Ini?", "Konfirmasi", JOptionPane.YES_NO_OPTION);

            if (confirmResult == JOptionPane.YES_OPTION) {
                try {
                    String kodeBarang = tblbarangkeluar.getValueAt(selectedRowIndex, 0).toString();
                    String deleteQuery = "DELETE FROM barang_keluar WHERE kode_barang = ?";

                    PreparedStatement st = con.prepareStatement(deleteQuery);
                    st.setString(1, kodeBarang);

                    int rowsAffected = st.executeUpdate();
                    if (rowsAffected > 0) {
                        JOptionPane.showMessageDialog(null, "Data Berhasil Dihapus");
                        // Refresh tabel setelah penghapusan
                        tabel2();
                    } else {
                        JOptionPane.showMessageDialog(null, "Data dengan Kode Barang " + kodeBarang + " tidak ditemukan");
                    }
                } catch (SQLException e) {
                    JOptionPane.showMessageDialog(null, "Error saat menghapus data: " + e.getMessage());
                }
            }
        } else {
            JOptionPane.showMessageDialog(null, "Pilih baris yang ingin dihapus");
        }
    }//GEN-LAST:event_btnhapus2ActionPerformed

    private void btninputbarangkeluarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btninputbarangkeluarActionPerformed
        // TODO add your handling code here:
        try {
            stat.executeUpdate("insert into barang_keluar values ("
                + "'" + tfkodebarang.getText() + "',"
                + "'" + tfnamabarang.getText() + "',"
                + "'" + tftanggalmasuk.getText() + "',"
                + "'" + tftanggalkeluar.getText() + "',"
                + "'" + tfjumlah.getText() + "',"
                + "'" + tfkondisi.getText() + "')");

            kosongkan();
            JOptionPane.showMessageDialog(null, "Data Berhasil Dikeluarkan");
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Perintah Salah : " + e);
        }
        new InventarisAset().setVisible(true);
        dispose();
    }//GEN-LAST:event_btninputbarangkeluarActionPerformed

    private void btnhapus1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnhapus1ActionPerformed
        int selectedRowIndex = tblbarangmasuk.getSelectedRow();
        if (selectedRowIndex != -1) {
            int confirmResult = JOptionPane.showConfirmDialog(null, "Apakah Anda Yakin Untuk Menghapus Data Ini?", "Konfirmasi", JOptionPane.YES_NO_OPTION);

            if (confirmResult == JOptionPane.YES_OPTION) {
                try {
                    String kodeBarang = tblbarangmasuk.getValueAt(selectedRowIndex, 0).toString();
                    String deleteQuery = "DELETE FROM barang_masuk WHERE kode_barang = ?";

                    PreparedStatement st = con.prepareStatement(deleteQuery);
                    st.setString(1, kodeBarang);

                    int rowsAffected = st.executeUpdate();
                    if (rowsAffected > 0) {
                        JOptionPane.showMessageDialog(null, "Data Berhasil Dihapus");
                        // Refresh tabel setelah penghapusan
                        tabel1();
                    } else {
                        JOptionPane.showMessageDialog(null, "Data dengan Kode Barang " + kodeBarang + " tidak ditemukan");
                    }
                } catch (SQLException e) {
                    JOptionPane.showMessageDialog(null, "Error saat menghapus data: " + e.getMessage());
                }
            }
        } else {
            JOptionPane.showMessageDialog(null, "Pilih baris yang ingin dihapus");
        }
    }//GEN-LAST:event_btnhapus1ActionPerformed

    private void btninputbarangmasukActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btninputbarangmasukActionPerformed
        // TODO add your handling code here:
        try {
            stat.executeUpdate("insert into barang_masuk values ("
                + "'" + tfkodebarang.getText() + "',"
                + "'" + tfnamabarang.getText() + "',"
                + "'" + tftanggalmasuk.getText() + "',"
                + "'" + tfjumlah.getText() + "',"
                + "'" + tfkondisi.getText() + "')");

            kosongkan();
            JOptionPane.showMessageDialog(null, "Berhasil Menyimpan Data");
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Perintah Salah : " + e);
        }
        new InventarisAset().setVisible(true);
        dispose();
    }//GEN-LAST:event_btninputbarangmasukActionPerformed

    private void tftanggalkeluarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tftanggalkeluarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tftanggalkeluarActionPerformed

    private void btnedit1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnedit1ActionPerformed
        // TODO add your handling code here:
        int selectedRowIndex = tblbarangkeluar.getSelectedRow();
        if (selectedRowIndex != -1) {
            int confirmResult = JOptionPane.showConfirmDialog(null, "Apakah Anda Yakin Untuk Update Data Ini???", "Confirmation", JOptionPane.YES_NO_OPTION);

            if (confirmResult == JOptionPane.YES_OPTION) {
                try {
                    String sql = "UPDATE barang_keluar SET kode_barang=?, nama_barang=?, tanggal_masuk=?,tanggal_keluar=?, jumlah=?, kondisi=? WHERE kode_barang=?";
                    PreparedStatement st = con.prepareStatement(sql);

                    st.setString(1, tfkodebarang.getText());
                    st.setString(2, tfnamabarang.getText());
                    st.setString(3, tftanggalmasuk.getText());
                    st.setString(4, tftanggalkeluar.getText());
                    st.setString(5, tfjumlah.getText());
                    st.setString(6, tfkondisi.getText());
                    st.setString(7, tblbarangkeluar.getValueAt(selectedRowIndex, 0).toString()); // Menggunakan nilai kode_barang dari baris yang dipilih

                    int rowsAffected = st.executeUpdate();
                    if (rowsAffected > 0) {
                        JOptionPane.showMessageDialog(null, "Update Data Berhasil");
                        new InventarisAset().setVisible(true);
                        dispose();
                    } else {
                        JOptionPane.showMessageDialog(null, "Tidak ada data yang diupdate");
                    }
                } catch (SQLException e) {
                    e.printStackTrace();
                    JOptionPane.showMessageDialog(null, "Update Data Gagal: " + e.getMessage());
                }
            }
        } else {
            JOptionPane.showMessageDialog(null, "Pilih baris yang ingin diupdate");
        }
    }//GEN-LAST:event_btnedit1ActionPerformed

    private void btncetak2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btncetak2ActionPerformed
        // TODO add your handling code here:
        try {
            // Load and compile the JasperReport
            JasperPrint jp = JasperFillManager.fillReport(
                getClass().getResourceAsStream("/laporan/laporan_barang_keluar.jasper"),
                new HashMap<>(),
                con
            );

            // Display the report using JasperViewer
            JasperViewer.viewReport(jp, false);
        } catch(Exception e) {
            JOptionPane.showMessageDialog(rootPane, e);
        }

        // ... other methods and variables ...
    }//GEN-LAST:event_btncetak2ActionPerformed

    private void btnhapusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnhapusActionPerformed
        // TODO add your handling code here:
        kosongkan();
    }//GEN-LAST:event_btnhapusActionPerformed

    private void tblbarangkeluarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblbarangkeluarMouseClicked
        // TODO add your handling code here:
        int i = tblbarangkeluar.getSelectedRow();
        if (i == -1) {
            return;
        }
        String code = (String) tblbarangkeluar.getValueAt(i, 0);
        String code1 = (String) tblbarangkeluar.getValueAt(i, 1);
        String code2 = (String) tblbarangkeluar.getValueAt(i, 2);
        String code3 = (String) tblbarangkeluar.getValueAt(i, 3);
        String code4 = (String) tblbarangkeluar.getValueAt(i, 4);
        String code5 = (String) tblbarangkeluar.getValueAt(i, 5);
        tfkodebarang.setText(code);
        tfnamabarang.setText(code1);
        tftanggalmasuk.setText(code2);
        tftanggalkeluar.setText(code3);
        tfjumlah.setText(code4);
        tfkondisi.setText(code5);
    }//GEN-LAST:event_tblbarangkeluarMouseClicked

    private void btncetakActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btncetakActionPerformed
        try {
            // Load and compile the JasperReport
            JasperPrint jp = JasperFillManager.fillReport(
                getClass().getResourceAsStream("/laporan/laporan_barang_masuk.jasper"),
                new HashMap<>(),
                con
            );

            // Display the report using JasperViewer
            JasperViewer.viewReport(jp, false);
        } catch(Exception e) {
            JOptionPane.showMessageDialog(rootPane, e);
        }

        // ... other methods and variables ...
    }//GEN-LAST:event_btncetakActionPerformed

    private void btneditActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btneditActionPerformed
        int selectedRowIndex = tblbarangmasuk.getSelectedRow();
        if (selectedRowIndex != -1) {
            int confirmResult = JOptionPane.showConfirmDialog(null, "Apakah Anda Yakin Untuk Update Data Ini???", "Confirmation", JOptionPane.YES_NO_OPTION);

            if (confirmResult == JOptionPane.YES_OPTION) {
                try {
                    String sql = "UPDATE barang_masuk SET kode_barang=?, nama_barang=?, tanggal_masuk=?, jumlah=?, kondisi=? WHERE kode_barang=?";
                    PreparedStatement st = con.prepareStatement(sql);

                    st.setString(1, tfkodebarang.getText());
                    st.setString(2, tfnamabarang.getText());
                    st.setString(3, tftanggalmasuk.getText());
                    st.setString(4, tfjumlah.getText());
                    st.setString(5, tfkondisi.getText());
                    st.setString(6, tblbarangmasuk.getValueAt(selectedRowIndex, 0).toString()); // Menggunakan nilai kode_barang dari baris yang dipilih

                    int rowsAffected = st.executeUpdate();
                    if (rowsAffected > 0) {
                        JOptionPane.showMessageDialog(null, "Update Data Berhasil");
                        new InventarisAset().setVisible(true);
                        dispose();
                    } else {
                        JOptionPane.showMessageDialog(null, "Tidak ada data yang diupdate");
                    }
                } catch (SQLException e) {
                    e.printStackTrace();
                    JOptionPane.showMessageDialog(null, "Update Data Gagal: " + e.getMessage());
                }
            }
        } else {
            JOptionPane.showMessageDialog(null, "Pilih baris yang ingin diupdate");
        }
    }//GEN-LAST:event_btneditActionPerformed

    private void tblbarangmasukMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblbarangmasukMouseClicked
        // TODO add your handling code here:
        int i = tblbarangmasuk.getSelectedRow();
        if (i > -1) {

        }
        String code = (String) tblbarangmasuk.getValueAt(i, 0);
        String code1 = (String) tblbarangmasuk.getValueAt(i, 1);
        String code2 = (String) tblbarangmasuk.getValueAt(i, 2);
        String code3 = (String) tblbarangmasuk.getValueAt(i, 3);
        String code4 = (String) tblbarangmasuk.getValueAt(i, 4);
        tfkodebarang.setText(code);
        tfnamabarang.setText(code1);
        tftanggalmasuk.setText(code2);
        tfjumlah.setText(code3);
        tfkondisi.setText(code4);
    }//GEN-LAST:event_tblbarangmasukMouseClicked
    
    
    
    public void tblbarangmasuk() {
        int a = 100;
        Object[][] data = new Object[a][8];
        try {
            int i = 0;
            while (res.next()) {
                data[1][0] = res.getString("kode_barang");
                data[1][1] = res.getString("nama_barang");
                data[1][2] = res.getString("tanggal_masuk");
                data[1][3] = res.getString("jumlah");
                data[1][4] = res.getString("kondisi");
                i++;
            }
            String[] setJudul = {"kode_barang", "nama_barang", "tanggal_masuk", "jumlah", "kondisi"};
            tblbarangmasuk.setModel(new DefaultTableModel(data, setJudul));
            data = new Object[1][8];
        } catch (Exception e) {
            System.out.println("Gagal Tampil" + e.toString());
        }
    }

    public void tblbarangkeluar() {
        int a = 100;
        Object[][] data = new Object[a][8];
        try {
            int i = 0;
            while (res.next()) {
                data[1][0] = res.getString("kode_barang");
                data[1][1] = res.getString("nama_barang");
                data[1][2] = res.getString("tanggal_masuk");
                data[1][3] = res.getString("tanggal_keluar");
                data[1][4] = res.getString("jumlah");
                data[1][5] = res.getString("kondisi");
                i++;
            }
            String[] setJudul = {"kode_barang", "nama_barang", "tanggal_masuk", "tanggal_keluar", "jumlah", "kondisi"};
            tblbarangkeluar.setModel(new DefaultTableModel(data, setJudul));
            data = new Object[1][8];
        } catch (Exception e) {
            System.out.println("Gagal Tampil" + e.toString());
        }
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(InventarisAset.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(InventarisAset.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(InventarisAset.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(InventarisAset.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new InventarisAset().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btncetak;
    private javax.swing.JButton btncetak2;
    private javax.swing.JButton btnedit;
    private javax.swing.JButton btnedit1;
    private javax.swing.JButton btnhapus;
    private javax.swing.JButton btnhapus1;
    private javax.swing.JButton btnhapus2;
    private javax.swing.JButton btninputbarangkeluar;
    private javax.swing.JButton btninputbarangmasuk;
    private javax.swing.JButton btnkeluar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable tblbarangkeluar;
    private javax.swing.JTable tblbarangmasuk;
    private javax.swing.JTextField tfjumlah;
    private javax.swing.JTextField tfkodebarang;
    private javax.swing.JTextField tfkondisi;
    private javax.swing.JTextField tfnamabarang;
    private javax.swing.JTextField tftanggalkeluar;
    private javax.swing.JTextField tftanggalmasuk;
    // End of variables declaration//GEN-END:variables

    private Statement excuteUpdate(String total) {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }

}
